<?php

    global $datacontainer;
    $time = new TimeAnalyze($messages[$i]['date']);
    $showpic = false;
    if (isset($messages[$i + 1])) {
        if($time->timestamp - 7200 > $messages[$i + 1]['date']) { 
            $showpic = true; ?>
            </div><div class="timestamp"><?=$time->getFormattedTime();?></div>
        <?php }
    }
    if (isset($messages[$i + 1]) and !$showpic) {
        if ($messages[$i]['from_id'] != $messages[$i + 1]['from_id']) { ?>
            </div>
            <div class="list-container">
                <div class="list-head">
                    <table>
                        <tbody>
                            <tr>
                                <td class="left-part">
                                    <img class="user-photo" src="<?=$datacontainer->getObjById($messages[$i]['from_id'])->getProfilePicture()?>">
                                    <div class="check">
                                        <img src="images/checked.png" class="checked-head">
                                    </div>
                                </td>
                                <td class="right-part">
                                    <div class="user-head-block">
                                        <a class="user-name-href" href="https://vk.com/id<?=$messages[$i]['from_id']?>"><?php echo $datacontainer->getObjById($messages[$i]['from_id'])->getName(); ?></a>
                                        <span class="user-head-timemark"><?=$time->getTime();?></span>
                                    </div>
                                    <?php if (!in_array($messages[$i]['from_id'], BLACKLIST)) { ?>
                                        <div class="msg-head-content"><?php
                                            echo str_replace("\n", '<br>', $messages[$i]['text']);
                                        ?><?php
                                            if (isset($messages[$i]['attachments'][0]['photo'])) {
                                                echo '<img src="'.(array_pop($messages[$i]['attachments'][0]['photo']['sizes'])['url']).'">';
                                            }
                                        ?></div>
                                    <?php } else { ?>
                                        <div class="msg-head-content">Сообщение не может быть показано.</div>
                                    <?php } ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
        <?php } else if (!$showpic) { ?>
            <div class="list-elem">
                <table>
                    <tbody>
                        <tr>
                            <td class="left-part">
                                <div class="check">
                                    <img src="images/checked.png" class="checked-body">
                                </div>
                            </td>
                            <td class="right-part">
                                <?php if (!in_array($messages[$i]['from_id'], BLACKLIST)) { ?>
                                    <div class="msg-head-content"><?php
                                        echo str_replace("\n", '<br>', $messages[$i]['text']);
                                    ?><?php
                                        if (isset($messages[$i]['attachments'][0]['photo'])) {
                                            echo '<img src="'.(array_pop($messages[$i]['attachments'][0]['photo']['sizes'])['url']).'">';
                                        }
                                    ?></div>
                                <?php } else { ?>
                                    <div class="msg-head-content">Сообщение не может быть показано.</div>
                                <?php } ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <?php }
    } else { ?>
        <div class="list-container">
            <div class="list-head">
                <table>
                    <tbody>
                        <tr>
                            <td class="left-part">
                                <img class="user-photo" src="<?=$datacontainer->getObjById($messages[$i]['from_id'])->getProfilePicture()?>">
                                <div class="check">
                                    <img src="images/checked.png" class="checked-head">
                                </div>
                            </td>
                            <td class="right-part">
                                <div class="user-head-block">
                                    <a class="user-name-href" href="https://vk.com/id<?=$messages[$i]['from_id']?>"><?php echo
                                        $datacontainer->getObjById($messages[$i]['from_id'])->getName(); ?></a>
                                    <span class="user-head-timemark"><?=$time->getTime();?></span>
                                </div>
                                <?php if (!in_array($messages[$i]['from_id'], BLACKLIST)) { ?>
                                    <div class="msg-head-content"><?php
                                        echo str_replace("\n", '<br>', $messages[$i]['text']);
                                    ?><?php
                                        if (isset($messages[$i]['attachments'][0]['photo'])) {
                                            echo '<img src="'.(array_pop($messages[$i]['attachments'][0]['photo']['sizes'])['url']).'">';
                                        }
                                    ?></div>
                                <?php } else { ?>
                                    <div class="msg-head-content">Сообщение не может быть показано.</div>
                                <?php } ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
    <?php }

?>
